apiVersion: v1
kind: Service
metadata:
  name: hello-service
spec:
  selector:
    app: hello
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30001
  type: NodePort

---
apiVersion: v1
kind: Service
metadata:
  name: world-service
spec:
  selector:
    app: world
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
      nodePort: 30002
  type: NodePort
